name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Terraform Deployment"]
    types:
      - completed  # Runs only when the first workflow is completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker image # to automate acrname and image version
      run: |
        az acr login --name acrsalvatoreleonardi 
        docker build -t acrsalvatoreleonardi.azurecr.io/my-app:latest . 
        docker push acrsalvatoreleonardi.azurecr.io/my-app:latest

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group myResourceGroup --name myAKSCluster
        kubectl apply -f ./kubernetes/deployment.yaml
