name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        az acr login --name MyACR
        docker build -t myacr.azurecr.io/my-app:${{ github.sha }} .
        docker push myacr.azurecr.io/my-app:${{ github.sha }}

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/my-app my-app=myacr.azurecr.io/my-app:${{ github.sha }}
